"""
Deployment Utilities
====================
Generate deployment-ready packages and config files for Vercel, Netlify, and GitHub Pages.
"""

import json
import zipfile
import io
from typing import Optional


def create_vercel_config(project_name: str = "ai-website") -> str:
    """Generate vercel.json configuration."""
    config = {
        "version": 2,
        "name": project_name,
        "builds": [
            {"src": "index.html", "use": "@vercel/static"}
        ],
        "routes": [
            {"src": "/(.*)", "dest": "/index.html"}
        ]
    }
    return json.dumps(config, indent=2)


def create_netlify_config() -> str:
    """Generate netlify.toml configuration."""
    return """[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://images.unsplash.com data:;"
"""


def create_github_pages_workflow() -> str:
    """Generate GitHub Pages deploy workflow YAML."""
    return """name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""


def create_deploy_package(
    html_code: str,
    platform: str = "vercel",
    project_name: str = "ai-website",
) -> tuple[bytes, str, str]:
    """
    Create a deployment-ready ZIP package.
    
    Args:
        html_code: The generated HTML
        platform: "vercel", "netlify", or "github_pages"
        project_name: Name for the project
        
    Returns:
        (zip_bytes, filename, mime_type)
    """
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Main HTML file
        zf.writestr("index.html", html_code)

        # README
        readme = f"""# {project_name}

Generated by AI Website Builder.

## Deploy

"""

        if platform == "vercel":
            zf.writestr("vercel.json", create_vercel_config(project_name))
            readme += """### Vercel
1. Install Vercel CLI: `npm i -g vercel`
2. Run `vercel` in this directory
3. Follow the prompts
"""

        elif platform == "netlify":
            zf.writestr("netlify.toml", create_netlify_config())
            readme += """### Netlify
1. Drag and drop this folder to [Netlify Drop](https://app.netlify.com/drop)
2. Or install CLI: `npm i -g netlify-cli`
3. Run `netlify deploy --prod`
"""

        elif platform == "github_pages":
            zf.writestr(".github/workflows/deploy.yml", create_github_pages_workflow())
            readme += """### GitHub Pages
1. Create a new GitHub repository
2. Push this folder to the `main` branch
3. GitHub Actions will automatically deploy
"""

        # Add a generic package.json for tooling
        package_json = {
            "name": project_name,
            "version": "1.0.0",
            "description": "AI-generated website",
            "scripts": {
                "dev": "npx serve .",
                "preview": "npx serve . -p 3000",
            }
        }
        zf.writestr("package.json", json.dumps(package_json, indent=2))
        zf.writestr("README.md", readme)

    buf.seek(0)
    return buf.getvalue(), f"{project_name}-{platform}.zip", "application/zip"
