"""
Export Utilities
================
Export generated HTML to different formats.
"""

import re


def export_html(html_code: str, filename: str = "index.html") -> tuple[str, str, str]:
    """Return (content, filename, mime_type) for HTML export."""
    return html_code, filename, "text/html"


def export_react_component(html_code: str) -> tuple[str, str, str]:
    """
    Convert HTML to a React functional component.
    Converts class → className, for → htmlFor, etc.
    """
    # Extract body content
    body_match = re.search(r'<body[^>]*>(.*?)</body>', html_code, re.DOTALL | re.IGNORECASE)
    body_content = body_match.group(1).strip() if body_match else html_code

    # Extract styles from <style> tags
    style_blocks = re.findall(r'<style[^>]*>(.*?)</style>', html_code, re.DOTALL | re.IGNORECASE)
    css_content = "\n".join(style_blocks)

    # Extract <head> meta content for reference
    head_match = re.search(r'<head[^>]*>(.*?)</head>', html_code, re.DOTALL | re.IGNORECASE)
    head_content = head_match.group(1).strip() if head_match else ""

    # Convert HTML attributes to JSX
    jsx_content = body_content
    jsx_content = re.sub(r'\bclass=', 'className=', jsx_content)
    jsx_content = re.sub(r'\bfor=', 'htmlFor=', jsx_content)
    jsx_content = re.sub(r'\bstroke-width=', 'strokeWidth=', jsx_content)
    jsx_content = re.sub(r'\bfill-rule=', 'fillRule=', jsx_content)
    jsx_content = re.sub(r'\bclip-rule=', 'clipRule=', jsx_content)
    jsx_content = re.sub(r'\bstroke-linecap=', 'strokeLinecap=', jsx_content)
    jsx_content = re.sub(r'\bstroke-linejoin=', 'strokeLinejoin=', jsx_content)
    jsx_content = re.sub(r'\btabindex=', 'tabIndex=', jsx_content)
    jsx_content = re.sub(r'\bviewbox=', 'viewBox=', jsx_content, flags=re.IGNORECASE)
    # Convert inline event handlers
    jsx_content = re.sub(r'\bonclick=', 'onClick=', jsx_content, flags=re.IGNORECASE)
    jsx_content = re.sub(r'\bonchange=', 'onChange=', jsx_content, flags=re.IGNORECASE)
    jsx_content = re.sub(r'\bonsubmit=', 'onSubmit=', jsx_content, flags=re.IGNORECASE)

    # Remove <script> tags (should be replaced with React hooks)
    jsx_content = re.sub(r'<script[^>]*>.*?</script>', '', jsx_content, flags=re.DOTALL | re.IGNORECASE)

    component_code = f'''import React, {{ useEffect, useState }} from 'react';
import './LandingPage.css';

/**
 * AI-Generated Landing Page Component
 * Generated by AI Website Builder
 */
export default function LandingPage() {{
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  useEffect(() => {{
    // Intersection Observer for fade-in animations
    const observer = new IntersectionObserver(
      (entries) => {{
        entries.forEach((entry) => {{
          if (entry.isIntersecting) {{
            entry.target.classList.add('animate-visible');
          }}
        }});
      }},
      {{ threshold: 0.1 }}
    );

    document.querySelectorAll('.animate-on-scroll').forEach((el) => {{
      observer.observe(el);
    }});

    return () => observer.disconnect();
  }}, []);

  return (
    <>
{jsx_content}
    </>
  );
}}
'''

    css_code = f'''/* AI-Generated Landing Page Styles */
{css_content}

.animate-on-scroll {{
  opacity: 0;
  transform: translateY(20px);
  transition: opacity 0.6s ease, transform 0.6s ease;
}}

.animate-visible {{
  opacity: 1;
  transform: translateY(0);
}}
'''

    # Combine as a single downloadable file with CSS embedded
    combined = f"// === LandingPage.jsx ===\n\n{component_code}\n\n// === LandingPage.css ===\n\n{css_code}"

    return combined, "LandingPage.jsx", "text/javascript"


def export_nextjs_page(html_code: str) -> tuple[str, str, str]:
    """
    Convert HTML to a Next.js page component with metadata export.
    """
    # Extract title
    title_match = re.search(r'<title>(.*?)</title>', html_code, re.IGNORECASE)
    title = title_match.group(1) if title_match else "AI-Generated Website"

    # Extract meta description
    desc_match = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', html_code, re.IGNORECASE)
    description = desc_match.group(1) if desc_match else ""

    # Get the React component (reuse the conversion)
    react_code, _, _ = export_react_component(html_code)

    nextjs_code = f'''import type {{ Metadata }} from 'next';

export const metadata: Metadata = {{
  title: '{title}',
  description: '{description}',
}};

{react_code}
'''

    return nextjs_code, "page.tsx", "text/typescript"
